### ISSUE TITLE
Question: Is it possible to prevent the use of `external` functions

### ISSUE THREAD

**Issue by richardmward** [camunda/feel-scala#102]
Is it possible to disable the use of external functions so that users wouldn't have access to any java class in the JVM?

**Comment by saig0** [comment]
Currently, it is not possible to prevent it. 

I understand that it makes sense for some cases to not allow this access. So, the FEEL code can not break out of the FEEL context.

What do you think about having a configuration option to disable this feature on creating the FEEL engine?
In which context do you need to disable it (e.g. Camunda platform plugin, ...)?

**Comment by richardmward** [comment]
A configuration option would be ideal. I use the standalone setup.

**Comment by saig0** [comment]
This issue has a high priority because it is an actual security risk (e.g. killing the application, execute commands, etc.). We should disable the external functions by default and have an option to enable it. 

FYI: @menski @tasso94 

I'm planning to implement it this week or the beginning of next week. Do you want to consider this as a bug? Or not and jump to the next major version since this changes the actual behavior?

**Comment by tasso94** [comment]
Hi Philipp,

I would go for a Bug and fix it on master as well as on 1.10. However, please let me first check with Thorben.

I'll come back to you as soon as we have discussed this.

Cheers,
Tassilo

**Comment by tasso94** [comment]
Hi Philipp,

I checked together with Thorben and we both agree that this issue should be handled as a bug.

Cheers,
Tassilo
