### ISSUE TITLE
Display a more expressive error message when using single-quoted string literals

### ISSUE THREAD

**Issue by tasso94** [camunda/feel-scala#114]
**Is your feature request related to a problem? Please describe.**
* Use a single-quoted string literal in a unary test (which is not allowed by the specification), e. g. 'asdfasdf'
* Evaluate the unary test
* The following error message is shown: `failed to evaluate expression 'asdfasdf': no variable found for name 'asdfasdf'`

**Describe the solution you'd like**
A more expressive error message is shown that the user can easier understand that a single-quoted string literal is not allowed and must be replaced by a double-quoted string literal.

**Comment by tasso94** [comment]
Related to issue: https://jira.camunda.com/browse/CAM-11515

**Comment by saig0** [comment]
The behavior changed since it was reported. In version `1.16.0`, the engine fails to evaluate the expression. 

For a unary-tests expression, it returns the following error message:

```
failed to parse expression ''asdfasdf'': Expected (negation | positiveUnaryTests | anyInput):1:1, found "'asdfasdf'"
```

For a regular expression, it returns the following error message:

```
failed to parse expression ''asdfasdf'': Expected (ifOp | forOp | quantifiedOp | disjunction):1:1, found "'asdfasdf'"
```

The error message is still cryptic but it is clear that the failure is about the parsing of the expression. :rocket: 

---

I don't see a strong need to improve the error message further. So, I'm closing the issue. 
Feel free to re-open the issue if there is any new input.
