### ISSUE TITLE
Add "current date" function

### ISSUE THREAD

**Issue by pabloromanelli** [camunda/feel-scala#118]
**Is your feature request related to a problem? Please describe.**
Hi, I need to calculate the age of a user based on its birthday using `zeebe-script-worker`. The problem is that I don't have the current date to subtract it from.

**Describe the solution you'd like**
I would like to have a function to get the current date, for example `date()`.

Thank you

**Comment by saig0** [comment]
Thank you for reporting :+1:  

I see that this function is important to do temporal calculations. I would suggest the following two functions:
* `today()` returns the current date 
* `now()` returns the current date and time (in the system time zone)

Unfortunately, these functions are not defined by the DMN spec yet. However, it makes to add them anyways.

The problem is how to get the current date/time. It is not always correct to use the Java/system clock. Instead, the application that uses/embeds the FEEL engine should provide the time. 

So, we could either say that this function needs to be implemented in every application (e.g. via Function Provider SPI) like in the Camunda platform, or the application can implement a clock API to provide the time/date.

**Comment by pabloromanelli** [comment]
Maybe generating a "new" date is not necessarily what I need.
If I could have a variable with the time when the workflow instance or the current job was created / activated, I could use it to do the calculations instead of a function.

Could this be a good solution without affecting the spec?
Do you have a recommendation on how to solve this if I wanted to use Camunda Cloud?

I'm trying not to create custom workers, for example using zeebe-script-worker. Maybe I could create a PR there with the added variables if you think this is a good idea.

**Comment by saig0** [comment]
@pabloromanelli, adding this function/variable in the worker would be possible. But since I see that it is also useful for other cases, I would prefer to implement it here once.

I think providing the current date as a function instead of a variable fits better with the spec. The spec already defines a lot of built-in functions. I also see other vendors that did the same.

Regarding the Camunda Cloud: currently, we're integrating the FEEL engine as expression language in Zeebe for all technical attributes (e.g. conditions, variable mapping, etc.). So, this will then be also available in the cloud.

In the context of Zeebe: is there a reason why we should use the creation time of the job/workflow instance of the current time of the broker?

**Comment by saig0** [comment]
@tasso94, any opinion about implementing both functions in the FEEL engine? 

Impact on Camunda BPM: `now()` function can be removed and `ClockProvider` needs to be implemented.

**Comment by pabloromanelli** [comment]
> In the context of Zeebe: is there a reason why we should use the creation time of the job/workflow instance of the current time of the broker?

I don't currently have a use case, but I can imagine a process where after waiting a long time for a message (e.g. an admin resolving some task), I could make a decision based on the time past since the start of the workflow.
The job start time could also be useful only if the job was activated with a long timeout on purpose (like zeebe-simple-tasklist is doing to move the responsibility to complete the task on another application).
