### ISSUE TITLE
Add built-in function for (commercial) rounding up 

### ISSUE THREAD

**Issue by bigpuritz** [camunda/feel-scala#167]
When performing DMN calculations, it is very often necessary to round off numbers commercially. (= `RoundingMode.HALF_UP`)

* **Is the function round() part of the DMN/FEEL specification?**

No, it is not. Source: https://www.omg.org/spec/DMN/1.2/PDF  (Page 149)

* **how is the function different from decimal(), floor() and ceiling()?**

The round()-function uses `RoundingMode.HALF_UP`  (decimal() uses `HALF_EVEN`, floor() uses `FLOOR`, ceiling() uses `CEILING`

* **in which context do you need this function? (i.e. Camunda BPM platform, Zeebe, something else)**

This function is needed in context of Camunda BPM platform (DMN calculations), but can be probably used in Zeebe too.

Referenced Pull-Request: #165

**Comment by saig0** [comment]
Thank you for raising this up :+1: 

I see the value of such a function. But I'm not sure about the name `round()`. For me, it hard to decide which of the functions does the rounding that I need. And what happens if we need another method for rounding `HALF_DOWN`.

What do you think about extending the `decimal()` function? It could have an optional third parameter to specify the rounding method. By default, it rounds `HALF_EVEN` to not break existing code but allows defining`HALF_UP`.

**Comment by bigpuritz** [comment]
Hi,

i've changed the pull request as you proposed. Now there is another version of the `decimal()` function with the third parameter for the rounding mode.
