### ISSUE TITLE
Add a function that extracts text based on regex

### ISSUE THREAD

**Issue by vincentgiraud** [camunda/feel-scala#315]
We need to extract a list of references (contract/client/ticket ids) from a text input and output them as a stringified list or a separated string of values (since a DMN output var value can only be string if I'm not wrong).

The custom function could have the following signature:

extract("input_text", "regular_expression")
e.g. extract("my references are 1234 and 1256", "12*") with the stringified list: "[1234, 1256]"
pro: no separator required in the following task
con: requires a string-to-list conversion function not available in FEEL

or alternatively

extract("input_text", "regular_expression", "separator")
e.g. extract("my references are 1234 and 1256", "12*", ";") with the val-sep string: "1234;1256"
pro: the following task can do a FEEL split(dmn-val-sep-values, ";")
con: requires to know the convention for which separator (e.g. ";") to use

**Related pull request**
https://github.com/camunda/feel-scala/pull/269

**Comment by saig0** [comment]
Thank you for reporting. I see the value of the proposed function. 

The problems with the existing functions:
* `replace()` 
  * is complicated if you want to ignore other parts of the string (i.e. negative lookahead)
  * is tricky if you don't know the number of matches
* `spit()` doesn't include the search string 

I suggest the following method signature for the new method to align with the existing string functions:

```
extract(input: string, pattern: string): list<string>
```

* two arguments:
  * `input`: string
  * `pattern`: regex as string
* return: a list of strings

I prefer returning a list of strings instead of a formatted string. It is more general and allows different uses cases.

In order to build the formatted string, I suggest a new function `join()` that works like Java's [joining()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Collectors.html#joining(java.lang.CharSequence,java.lang.CharSequence,java.lang.CharSequence)). This function can be useful also in other cases. 

@vincentgiraud does the suggestion make sense for you?

---

As a workaround, you could use the following expression to extract and format the string:

```
{
  separator: ", ",
  matches: replace("my references are 1234 and 1256","\D*(12\d*)","$1" + separator),
  result: replace(matches, "(.*)" + separator, "[$1]")
}.result
```
