### ISSUE TITLE
`string join` list function not evaluated / failed to parse

### ISSUE THREAD

**Issue by julrichkieffer** [camunda/feel-scala#405]
**Describe the bug**
`Unable to compile script: failed to parse expression` exception whenever `string join` is used

**To Reproduce**
1. In Camunda Modeler [sic], within a task's configuration create an output parameter with type `Script` of format `FEEL` for each of:
- `string join( ["foo","bar","baz"] )`
- `string join( ["foo","bar","baz"] , "::")`
- `string join( ["foo","bar","baz"] , "::", "hello-", "-goodbye")`
2. Publish and start the process

**Expected behavior**
3 output parameters should create 3 corresponding process variables (see Cockpit) with values:
- `foobarbaz`
- `foo::bar::baz`
- `hello-foo::bar::baz-goodbye`

**Actual behavior**
Instead of the above expected behaviour, the following error is thrown:

> The process could not be started. :
Cannot instantiate process definition task-assignment-by-dmn:15:07acd72a-8a7f-11ec-b269-0242ac110005: Unable to compile script: failed to parse expression 'string join( ["foo","bar","baz"] , "::", "hello-", "-goodbye")':
Expected (StringIn("<=", ">=", "<", ">", "!=", "=") | "between" | "in" | "and" | "or" | end-of-input):1:8, found "join( [\"fo"

**Environment**
* JRE 11
* Spring-Boot:  (v2.5.4)
* Camunda Platform: (v7.16.0)
* Camunda Platform Spring Boot Starter: (v7.16.0)
* FEEL engine version: feel-engine-1.13.1-scala-shaded.jar:1.13.1 **from stack trace**
* Affects: 
  * Camunda Automation Platform 7: [7.x] 
  * Zeebe broker: [0.x]

**Comment by saig0** [comment]
@julrichkieffer thank you for reporting :+1: 

I can verify the parsing failure with version `1.13.1`. But the failure is fixed with version `1.14.0`. Since the function `string join()` is only available since version `1.14.0`, I don't see any issue here :sweat_smile: 

> How do I configure my SpringBoot starter project (Maven) to dynamically load v1.14.2 (latest .jar) instead? Or, will v1.14.2 be bundled with an updated Camunda e.g. v7.16.1?

Good question. Since you're using the Spring Boot starter, you could override the dependency to the FEEL engine by importing the engine separately in the new version.

**Comment by julrichkieffer** [comment]
Hi

I downloaded the latest version (.jar) and added a `system` dependancy in
Maven, which loaded the newer FEEL engine. But Spring / Camunda didn't use
the newer engine, I think because an impl class isn't in the standalone
.jar. 🤷🏽‍♂️

I don't know Spring, Java or Maven so I gave up by deciding to wait for
Camunda Platform to release a new version. I didn't try Camunda Run — where
it auto detects jars.

**Comment by saig0** [comment]
A Camunda Spring Boot project should be set up as described in the [guide](https://docs.camunda.org/get-started/spring-boot/project-setup/#add-camunda-platform-spring-boot-dependencies). It should be possible to change the version of the FEEL engine with the following modifications to the `pom.xml`:

```
<dependency>
      <groupId>org.camunda.bpm.springboot</groupId>
      <artifactId>camunda-bpm-spring-boot-starter-webapp</artifactId>
      <version>7.16.0</version>
      <exclusions>
        <exclusion>
          <groupId>org.camunda.feel</groupId>
          <artifactId>feel-engine</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.camunda.feel</groupId>
      <artifactId>feel-engine</artifactId>
      <version>1.14.2</version>
      <classifier>scala-shaded</classifier>
    </dependency>
```

But I didn't try it out completely. 

Otherwise, feel free to wait until the new FEEL version is shipped with the Camunda distribution.
