### ISSUE TITLE
range function before/after are failing with date and time objects

### ISSUE THREAD

**Issue by McAlm** [camunda/feel-scala#428]
**Describe the bug**
The FEEL expression
`after(date and time(now()), date and time(today(),time("14:00:00")))`
fails with 
`14:44:02.988 [main] WARN  org.camunda.feel.FeelEngine - Suppressed failure: illegal arguments: List(ValDateTime(2022-05-13T14:44:02.987611+02:00[Europe/Berlin]))
14:44:02.990 [main] WARN  org.camunda.feel.FeelEngine - Suppressed failure: illegal arguments: List(ValNull, ValLocalDateTime(2022-05-13T14:00))`

**Expected behavior**
range functions work as documented

**Environment**
* FEEL engine version: FEEL Engine REPL (1.14.2) Ammonite Repl 2.5.3 (Scala 2.13.8 Java 11.0.13) | also: zeebe_8.0.1

**Comment by saig0** [comment]
@McAlm thank you for reporting. 

The issue with this expression is not the `after()` function. It's the function call `date and time(now())` because `date and time()` expected either a string or a date and a time argument.

You could fix the expression by using only `now()` and adding an offset to the time:

```
after(now(), date and time(today(),time("14:00:00+02:00")))
```

Or, without time offset/zone-id:

```
after(date and time(today(), time(now().hour, now().minute, now().second)), date and time(today(),time("14:00:00")))
```

![image](https://user-images.githubusercontent.com/4305769/168514881-7fd4784e-bbaa-48e0-b68e-42c548b643ad.png)

Does this help you?
