### ISSUE TITLE
FEEL Playground fails with timeout for expression: "1.50" > 0

### ISSUE THREAD

**Issue by falko** [camunda/feel-scala#579]
**Describe the bug**
The FEEL Playground in the docs fails with a timeout error for expression: "1.50" > 0

**To Reproduce**
1. Enter expression: "1.50" > 0

**Expected behavior**
A type mismatch warning is shown and null is returned.
Bonus points for pointing out that the `number()` function could be used for type conversion + link to [conversion functions](https://camunda.github.io/feel-scala/docs/reference/builtin-functions/feel-built-in-functions-conversion)

**Environment**
Even though it surfaced in the playground, it could indicate an engine issue.

**Comment by saig0** [comment]
@falko thank you for reporting. 

This is a current limitation of the playground. It is not able to return the failure if the expression is invalid. 

The underlying issue is that the evaluation is done via a process with a business rule task. :sweat_smile: 
We can lift this limitation with the new Zeebe DMN API that will come with version `8.2`.

**Comment by saig0** [comment]
This issue was fixed by replacing the playground backend (#630). :rocket:  

![image](https://github.com/camunda/feel-scala/assets/4305769/8a9f4b29-f7bc-49c0-957c-8b35ee455e25)
