### ISSUE TITLE
Provide isNaN() function equivalent to JavaScript

### ISSUE THREAD

**Issue by McAlm** [camunda/feel-scala#623]
**Is your feature request related to a problem? Please describe.**
In a map of contexts there are several key-value pairs which we need to pass one-by-one to a decision. All columns on the decision table are of type "String". When a numeric value should be checked (> 0) the number(myStringValue) is working fine, but when a String is passed to this decision the number("palim") function fails...

**Describe the solution you'd like**
By having a isNaN function one could check for the actual type first before calling number().

**Related issues**

**Comment by saig0** [comment]
The DMN spec says to use `null` for NaN:

![image](https://user-images.githubusercontent.com/4305769/234471288-e4a82f25-fdfa-4fcd-abef-eea07090aca4.png)

(DMN 1.4, page 107)

---

Instead of adding a new function `isNaN()`, we should fix the `number()` function. The function should not fail if the given string is not a number, but it should return `null`. 

This is a common behavior for all built-in functions. There is a related [test case](https://github.com/camunda/dmn-tck/blob/0b613499cd5fe5c49bd99e8c89dc6a13bc425adb/TestCases/compliance-level-3/0058-feel-number-function/0058-feel-number-function.dmn#L166-L174) in the DMN TCK about the expected behavior.

--- 

@McAlm do you agree? 
If yes, we can morph the issue into a bug report.

**Comment by saig0** [comment]
Closing this issue in favor of the bug issue: https://github.com/camunda/feel-scala/issues/731.
