### ISSUE TITLE
List projection if not all items have the given key

### ISSUE THREAD

**Issue by McAlm** [camunda/feel-scala#624]
**Is your feature request related to a problem? Please describe.**
We have a context like this:

```
[{"QUESTIONARE":"SCHADEN.SACH"},
{"ROLLE":"VN"},
{"SCHILDERUNG":"bla."},
{"ROLLE2":"GES"},
{"SCHILDERUNG2":"blubber."},
{"ROLLE3":"VN"},
{"SCHILDERUNG3":"Palim."},
{"WASGANZANDERES":"blau"},
{"ANZAHL_KAPUTTE_STUEHLE":5}]
```

Filtering for QUESTIONARE works fine:
```
[{"QUESTIONARE":"SCHADEN.SACH"},
{"ROLLE":"VN"},
{"SCHILDERUNG":"bla."},
{"ROLLE2":"GES"},
{"SCHILDERUNG2":"blubber."},
{"ROLLE3":"VN"},
{"SCHILDERUNG3":"Palim."},
{"WASGANZANDERES":"blau"},
{"ANZAHL_KAPUTTE_STUEHLE":5}].QUESTIONARE[1]
```

But for another key (e.g. `WASGANZANDERES`) it fails. Reason for that being the fact that the keys are different in all given contexts.

**Describe the solution you'd like**
The filter should work also on lists of contents with different keys.

If a context doesn't have the key then the list contains `null` for this context. 

For the example, it should return:

```
// expression
[{"QUESTIONARE":"SCHADEN.SACH"},
{"ROLLE":"VN"},
{"SCHILDERUNG":"bla."},
{"ROLLE2":"GES"},
{"SCHILDERUNG2":"blubber."},
{"ROLLE3":"VN"},
{"SCHILDERUNG3":"Palim."},
{"WASGANZANDERES":"blau"},
{"ANZAHL_KAPUTTE_STUEHLE":5}].WASGANZANDERES

// result
[null, null, null, null, null, null, null, "blue", null] 
```

_EDIT: updated the expected behavior based on the [comment](https://github.com/camunda/feel-scala/issues/624#issuecomment-1545354891)._

**Related issues**

* Camunda Autormation Platform 7: 
* Zeebe broker:

**Comment by saig0** [comment]
@McAlm thank you for reporting. :+1: 

Here is a simple example that demonstrates the issue:

```
[{x: 1}, {y: 2}].x
```

### The problem
Not all contexts of the list have a key `x`. 

### Actual behavior
It returns a list that contains an error. :see_no_evil: If the expression access the second item, the evaluation fails with an error.    

![image](https://github.com/camunda/feel-scala/assets/4305769/d7d7b2de-dd5b-4de4-a836-c7230711beef)

### Expected behavior
It returns a list that contains `null` if a context doesn't have this key.

```
[{x: 1}, {y: 2}].x
// should return:
// [1, null]
```

The expected behavior was discussed in the DMN TCK [here](https://github.com/dmn-tck/tck/pull/540#issuecomment-1438134609).

**Comment by saig0** [comment]
@McAlm I updated the expected behavior in the description to align with the discussion in the DMN TCK. 

It might not align with your expectations. The resulting list would return `null` values if the context doesn't contain the key. 

If you want to access the first item that is not null, you would need to filter the list before. 

For example:

```
my_list.WASGANZANDERES[item != null][1]
```

Does this work for you?

**Comment by saig0** [comment]
Closing this issue in favor of https://github.com/camunda/feel-scala/issues/674. This behavior is covered by the referenced issue.
