### ISSUE TITLE
The function `date()` doesn't return `null` for invalid dates

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#867]
**Describe the bug**
I can invoke the function `date()` with an invalid date, for example, `"2023-02-29"`. I expected `null` but the function returns the last date of the month.

**To Reproduce**
1. Evaluate the expression `date("2023-02-29")`
2. Verify that the result is a date at `"2023-02-28"`

**Expected behavior**
The function `date()` returns `null` if the date is invalid.

To be consistent, we should also return `null` for date literals, date-time literals, and the `date and time()` function if the date is invalid.

**Environment**
* FEEL engine version: `1.17.7`
* Affects: 
  * Camunda Automation Platform 7: [7.x] 
  * Zeebe broker: [0.x] 
  * Support: https://jira.camunda.com/browse/SUPPORT-22372
* OMG: https://issues.omg.org/browse/DMN17-67

**Comment by saig0** [comment]
:warning: The expected behavior is not defined in the DMN 1.5 specification. And, there is no test case in the DMN TCK ([ref](https://github.com/camunda/dmn-tck/tree/master/TestCases/compliance-level-3/1115-feel-date-function)).

**Comment by niekVandebron** [comment]
I was requested to provide a specific use case:

We don’t have a detailed use case other than parsing a date from a string coming from a request body (we do it in a few tasks).
But since we are new to feel/camunda we were experimenting with the date object and deciding if we wanted all of our date manipulations to happen within the APIs called via the REST connectors (in scala) or to keep them in the model (the easiest option).

Leap years are one of the first things you test when working with dates, so that's how we came across this issue.

**Comment by saig0** [comment]
:inbox_tray: I reported the issue to the OMG: https://issues.omg.org/issues/lists/unclassified#issue-54671.
