### ISSUE TITLE
Defining and invoking a user defined function in a process context does not work

### ISSUE THREAD

**Issue by jphillips-bp3** [camunda/feel-scala#874]
**Describe the bug**
The documentation link below implies that user defined functions can be defined and executed in a process context, but this does not work.

https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-functions/#user-defined

I can define and execute functions inside a DMN literal decision, but not within a process context.

**To Reproduce**
I created a simple BPMN to try this out. Here is how I can reproduce the issue:

1. In my start event I defined the following variable with the function:

![image](https://github.com/camunda/feel-scala/assets/4510278/696c877c-8b3e-4047-a920-b156b72c9e78)

2. I then called the function from a Script Task: 

![image](https://github.com/camunda/feel-scala/assets/4510278/5d92e04a-e774-4608-b031-fe8859c04c7a)

3. When invoked, the `scriptResult` variable was `null`:

![image](https://github.com/camunda/feel-scala/assets/4510278/f75f5f47-69a7-4829-b010-2c962e9f6f40)

**Expected behavior**
Given the documentation, I would expect the function to be called and in this example, `scriptResult` to have the value of `3`.

**Environment**
Tested on SaaS:

![image](https://github.com/camunda/feel-scala/assets/4510278/3a520759-cf52-4c14-94ce-426bb25fffe1)

**Comment by saig0** [comment]
@jphillips-bp3 thank you for reporting. :+1: 

I'm sorry for this confusion but Camunda doesn't support this feature. You can define a function and use it inside the same expression (e.g. in a script task expression or a variable mapping). See the example [here](https://camunda.github.io/feel-scala/docs/learn/samples/context-samples#structure-a-calculation). But, it is not possible to serialize/store the function, for example, in a process variable. 

However, I see the value in providing common functions for BPMN. Since this is more related to Camunda itself, please open a feature request [here](https://github.com/camunda/camunda/issues) as "Zeebe Feature request" and describe your use case in detail. :rocket:

**Comment by jphillips-bp3** [comment]
Feature request created here: https://github.com/camunda/camunda/issues/20141
