### ISSUE TITLE
Unexpected filter behaviour when using same value for iteration variable and context item

### ISSUE THREAD

**Issue by jjettenCamunda** [camunda/feel-scala#877]
**Describe the bug**
When using a variable to filter contexts inside of a context that declares an entry with the same name, the filter does not work and always evaluates to true.

**To Reproduce**
1. Create a list of objects, for example:
```
{
  "name_list": [{"name": "Bob"},{"name": "Bob"},{"name": "Bob"},{"name": "Tom"},{"name": "Tom"}]
}
```
2. Iterate over that list to build a new list of objects, one of the paths of the object has the same name as the iteration variable, for example: 
```
for name in ["Bob", "Tom", "Alice"]  return {"name": name, "count": count(name_list[item.name = name])}
```
3. Check the result, the filter has passed back the whole list and all the counts will be the total list size:
![image](https://github.com/camunda/feel-scala/assets/97948434/c2d35420-8e03-4df1-8e86-889e2cc439cd)

**Expected behavior**
I can see how variable shadowing could happen in this case, but I would expect either:
- It takes the value of the iteration variable
- or, it takes the value of the context
- or, it throws an error because it is unclear

For example(if name and name_2 where the same):
<img width="1140" alt="image" src="https://github.com/camunda/feel-scala/assets/97948434/da448ff9-c462-4ca2-be77-805eae447b55">

**Environment**
* FEEL engine version: [1.17.7] (playground)
* Affects: 
  * Camunda Automation Platform 7: [7.x] ??
  * Zeebe broker: [8.5+gen7]

**Comment by saig0** [comment]
@jjettenCamunda thank you for reporting. :+1: 

I see your confusion. However, I would argue that the behavior is correct. 

Why? In a filter expression, you can access the context entries of the list item by their name. In the example, the property name `name` shadows the iteration variable `name` (because it is closer from a scoping perspective). As a result, the condition `[item.name = name]` compares the same value and returns always `true`. 

The behavior is consistent in FEEL-Scala ([ref](https://camunda.github.io/feel-scala/docs/playground/?expression=Zm9yIG5hbWUgaW4gWyJCb2IiLCAiVG9tIiwgIkFsaWNlIl0gIHJldHVybiB7Im5hbWUiOiBuYW1lLCAiY291bnQiOiBjb3VudChuYW1lX2xpc3RbaXRlbS5uYW1lID0gbmFtZV0pfQ%3D%3D&context=ewogICJuYW1lX2xpc3QiOiBbeyJuYW1lIjogIkJvYiJ9LHsibmFtZSI6ICJCb2IifSx7Im5hbWUiOiAiQm9iIn0seyJuYW1lIjogIlRvbSJ9LHsibmFtZSI6ICJUb20ifV0KfQ%3D%3D&expression-type=expression)) and FEEL-JS ([ref](https://nikku.github.io/feel-playground/?e=%7E3YCAkIDngICAgICAgICzm0ompz7AVK3mFXhbIgcJxmd86NY6s0clRAeTLCglAj%2BK8fLuRLPPmnb20Q3bNHEOgWSao%2Biv%2FhoFRr%2BqmyKJS%2BtO0hIadDx07yy%2BJQMGI03%2F8CaTyQsffuZMgA%3D%3D&c=%7E3YCAkIDkgICAgICAgIC9AgCXnK4LCR%2BnRL%2B0%2B9jyBxlSiZUUppqxDCwlpjakgbZkG%2FGxdqwGS3H%2BOLv%2Ffn2MgA%3D%3D&t=expression&st=false)). 

However, we should document the behavior in the [docs](https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-list-expressions/#filter) clearly to avoid confusion. 

---

@jjettenCamunda does this make sense to you?

**Comment by jjettenCamunda** [comment]
I think it does, better documentation would have certainly helped, the use case of a list of objects seems common enough in my experience to have some examples in the docs on how to best handle them.

**Comment by saig0** [comment]
The behavior is described in the docs here: https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-context-expressions/.

So, nothing to do for now. Let's close the issue. :rocket:
